# -*- coding: utf-8 -*-
"""Comprehensive city to country mapping for Tab 5 global comparison."""

CITY_TO_COUNTRY = {
    # ── UNITED STATES ──────────────────────────────────────
    'USA': 'United States', 'US': 'United States',
    'United States of America': 'United States',
    'United Status': 'United States',
    'New York': 'United States', 'Manhattan': 'United States',
    'Brooklyn': 'United States', 'San Francisco': 'United States',
    'Los Angeles': 'United States', 'Los Angeles Country': 'United States',
    'Seattle': 'United States', 'Austin': 'United States',
    'Boston': 'United States', 'Chicago': 'United States',
    'Santa Monica': 'United States', 'Santa Clara': 'United States',
    'San Jose': 'United States', 'San Mateo': 'United States',
    'San Diego': 'United States', 'San Rafael': 'United States',
    'San Carlos': 'United States', 'San Ramon': 'United States',
    'San Antonio': 'United States', 'San Marcos': 'United States',
    'San Angelo': 'United States', 'San Francisco / London': 'United States',
    'Irvine': 'United States', 'Redwood City': 'United States',
    'Palo Alto': 'United States', 'Mountain View': 'United States',
    'Sunnyvale': 'United States', 'Cupertino': 'United States',
    'Menlo Park': 'United States', 'Foster City': 'United States',
    'Bellevue': 'United States', 'Kirkland': 'United States',
    'Redmond': 'United States', 'Renton': 'United States',
    'Bothell': 'United States', 'Tukwila': 'United States',
    'El Segundo': 'United States', 'Burbank': 'United States',
    'Glendale': 'United States', 'Culver City': 'United States',
    'Woodland Hills': 'United States', 'Hollywood': 'United States',
    'West Hollywood': 'United States', 'Beverly Hills': 'United States',
    'Long Beach': 'United States', 'Carlsbad': 'United States',
    'Costa Mesa': 'United States', 'Irvine': 'United States',
    'Novato': 'United States', 'Los Gatos': 'United States',
    'Aliso Viejo': 'United States', 'Redondo Beach': 'United States',
    'Palmdale': 'United States', 'Chula Vista': 'United States',
    'El Paso': 'United States', 'Riverside': 'United States',
    'Anaheim': 'United States', 'Camarillo': 'United States',
    'Palm Springs': 'United States', 'Palm Desert': 'United States',
    'Palm Beach Gardens': 'United States',
    'Nashville': 'United States', 'Atlanta': 'United States',
    'Alpharetta': 'United States', 'Marietta': 'United States',
    'Dallas': 'United States', 'Fort Worth': 'United States',
    'Houston': 'United States', 'Austin': 'United States',
    'Plano': 'United States', 'Irving': 'United States',
    'Grand Prairie': 'United States', 'Frisco': 'United States',
    'Denton': 'United States', 'Arlington': 'United States',
    'Denver': 'United States', 'Boulder': 'United States',
    'Colorado Springs': 'United States', 'Littleton': 'United States',
    'Broomfield': 'United States', 'Fort Collins': 'United States',
    'Loveland': 'United States', 'Highlands Ranch': 'United States',
    'Lakewood': 'United States', 'Greenwood Village': 'United States',
    'Phoenix': 'United States', 'Scottsdale': 'United States',
    'Tempe': 'United States', 'Chandler': 'United States',
    'Mesa': 'United States', 'Glendale': 'United States',
    'Peoria': 'United States', 'Tucson': 'United States',
    'Las Vegas': 'United States', 'Henderson': 'United States',
    'Reno': 'United States', 'Elko': 'United States',
    'Orlando': 'United States', 'Tampa': 'United States',
    'Miami': 'United States', 'Miami Beach': 'United States',
    'Fort Lauderdale': 'United States', 'Jacksonville': 'United States',
    'Tallahassee': 'United States', 'Boca Raton': 'United States',
    'Clearwater': 'United States', 'Cape Canaveral': 'United States',
    'Estero': 'United States', 'Lake Buena Vista': 'United States',
    'Temecula': 'United States', 'Winter Garden': 'United States',
    'Port Orange': 'United States', 'Oakland Park': 'United States',
    'Pembroke Pines': 'United States', 'Plantation': 'United States',
    'Doral': 'United States', 'Juno Beach': 'United States',
    'St. Louis': 'United States', 'Kansas City': 'United States',
    'Springfield': 'United States', 'Saint Charles': 'United States',
    'Wentzville': 'United States', 'Creve Coeur': 'United States',
    'Fenton': 'United States', 'St. Peters': 'United States',
    'Indianapolis': 'United States', 'Bloomington': 'United States',
    'Fort Wayne': 'United States', 'Columbus': 'United States',
    'Cincinnati': 'United States', 'Cleveland': 'United States',
    'Toledo': 'United States', 'Dayton': 'United States',
    'Philadelphia': 'United States', 'Pittsburgh': 'United States',
    'Pawtucket': 'United States', 'Bensalem': 'United States',
    'Moorestown': 'United States', 'Mount Laurel Township': 'United States',
    'Newark': 'United States', 'Hoboken': 'United States',
    'Princeton': 'United States', 'Parsippany-Troy Hills': 'United States',
    'Edison': 'United States', 'Westfield': 'United States',
    'Reston': 'United States', 'Herndon': 'United States',
    'Centreville': 'United States', 'Fairfax': 'United States',
    'Alexandria': 'United States', 'Bethesda': 'United States',
    'Annapolis Junction': 'United States', 'Washington': 'United States',
    'Charlotte': 'United States', 'Raleigh': 'United States',
    'Durham': 'United States', 'Greensboro': 'United States',
    'Winston-Salem': 'United States', 'Greenville': 'United States',
    'Spartanburg': 'United States',
    'Salt Lake City': 'United States', 'Lehi': 'United States',
    'Cottonwood Heights': 'United States', 'Alta': 'United States',
    'Taylorsville': 'United States',
    'Portland': 'United States', 'Beaverton': 'United States',
    'Hillsboro': 'United States', 'Eugene': 'United States',
    'Minneapolis': 'United States', 'Saint Paul': 'United States',
    'Minnetonka': 'United States', 'Bloomington': 'United States',
    'Northfield': 'United States',
    'Milwaukee': 'United States', 'Madison': 'United States',
    'Wauwatosa': 'United States', 'Green Bay': 'United States',
    'Waukegan': 'United States', 'Chicago': 'United States',
    'Naperville': 'United States', 'Itasca': 'United States',
    'Rosemont': 'United States', 'Addison': 'United States',
    'Tinley Park': 'United States', 'Scherereville': 'United States',
    'Detroit': 'United States', 'Troy': 'United States',
    'Southfield': 'United States', 'Auburn Hills': 'United States',
    'Ann Arbor': 'United States', 'Lansing': 'United States',
    'Grand Rapids': 'United States', 'Kalamazoo': 'United States',
    'Okemos': 'United States',
    'Baltimore': 'United States', 'Towson': 'United States',
    'Bowie': 'United States', 'Rockville': 'United States',
    'Buffalo': 'United States', 'Rochester': 'United States',
    'Albany': 'United States', 'Syracuse': 'United States',
    'Utica': 'United States', 'Ithaca': 'United States',
    'Hempstead': 'United States', 'Hauppauge': 'United States',
    'Farmingdale': 'United States', 'Lindenhurst': 'United States',
    'Babylon': 'United States', 'Jericho': 'United States',
    'Garden City': 'United States', 'Uniondale': 'United States',
    'New Haven': 'United States', 'Stamford': 'United States',
    'Ridgefield': 'United States', 'Westford': 'United States',
    'Providence': 'United States', 'Woonsocket': 'United States',
    'Pawtucket': 'United States',
    'Oklahoma City': 'United States', 'Tulsa': 'United States',
    'Bentonville': 'United States', 'Little Rock': 'United States',
    'Memphis': 'United States', 'Knoxville': 'United States',
    'Chattanooga': 'United States', 'Johnson City': 'United States',
    'Des Moines': 'United States', 'Cedar Falls': 'United States',
    'Davenport': 'United States', 'Iowa City': 'United States',
    'Omaha': 'United States', 'Lincoln': 'United States',
    'Sioux Falls': 'United States', 'Rapid City': 'United States',
    'Bismarck': 'United States', 'Minot': 'United States',
    'Huntsville': 'United States', 'Birmingham': 'United States',
    'Mobile': 'United States', 'Montgomery': 'United States',
    'Tuscaloosa': 'United States', 'Alabaster': 'United States',
    'Hoover': 'United States',
    'Baton Rouge': 'United States', 'New Orleans': 'United States',
    'Metairie': 'United States', 'Shreveport': 'United States',
    'Jackson': 'United States', 'Hattiesburg': 'United States',
    'Columbia': 'United States', 'Greenville': 'United States',
    'Charleston': 'United States',
    'Louisville': 'United States', 'Lexington': 'United States',
    'Andover': 'United States', 'Leominster': 'United States',
    'Waltham': 'United States', 'Woburn': 'United States',
    'North Andover': 'United States', 'Salem': 'United States',
    'Merrimack': 'United States', 'Nashua': 'United States',
    'Concord': 'United States', 'Hooksett': 'United States',
    'Augusta': 'United States', 'Gardiner': 'United States',
    'Harrisburg': 'United States', 'Trenton': 'United States',
    'Pittsburgh': 'United States', 'Albuquerque': 'United States',
    'Fayetteville': 'United States', 'Bentonville': 'United States',
    'Fort Collins': 'United States', 'Longmont': 'United States',
    'Bozeman': 'United States', 'Helena': 'United States',
    'Missoula': 'United States', 'Billings': 'United States',
    'Cheyenne': 'United States', 'Laramie': 'United States',
    'Tacoma': 'United States', 'Spokane': 'United States',
    'Silverdale': 'United States', 'Bremerton': 'United States',
    'Honolulu': 'United States',
    'Westlake': 'United States', 'Westlake Village': 'United States',
    'King of Prussia': 'United States', 'Paoli': 'United States',
    'West Chester': 'United States', 'Evanston': 'United States',
    'Lenexa': 'United States', 'Suwanee': 'United States',
    'Duluth': 'United States', 'Alpharetta': 'United States',
    'Woodbury': 'United States', 'Maplewood': 'United States',
    'Morrisville': 'United States', 'Apex': 'United States',
    'Cary': 'United States', 'Raleigh': 'United States',
    'Durham': 'United States', 'Chapel Hill': 'United States',
    'Ashville': 'United States',
    'Sacramento': 'United States', 'Folsom': 'United States',
    'Roseville': 'United States', 'Livermore': 'United States',
    'Fremont': 'United States', 'Oakland': 'United States',
    'Berkeley': 'United States', 'Emeryville': 'United States',
    'Hayward': 'United States', 'Newark': 'United States',
    'New Albany': 'United States', 'Plainview': 'United States',
    'Courtland': 'United States', 'Woodmere': 'United States',
    'Merrick': 'United States', 'Lynbrook': 'United States',
    'Islandia': 'United States', 'Woodbridge Township': 'United States',
    'Solon': 'United States', 'Strongsville': 'United States',
    'Mount Pleasant': 'United States', 'Rockford': 'United States',
    'Peoria': 'United States', 'Champaign': 'United States',
    'Urbana': 'United States', 'Decatur': 'United States',
    'Joliet': 'United States', 'Aurora': 'United States',
    'Elgin': 'United States', 'Waukegan': 'United States',
    'Evanston': 'United States', 'Schaumburg': 'United States',
    'Lombard': 'United States', 'Villa Park': 'United States',
    'Woodbury': 'United States',
    'Remote': 'United States',
    'USA/Canada preferred': 'United States',
    'Los angeles or Irvine': 'United States',
    'El Segudno': 'United States',
    'Huntington Beach': 'United States',
    'Morristown': 'United States',
    'Mount Dora': 'United States',
    'Topeka': 'United States',
    'Lafayette': 'United States',
    'Panama City': 'United States',
    'Reston': 'United States',
    'Middleton': 'United States',
    'Middletown': 'United States',
    'Middleburg': 'United States',
    'Herndon': 'United States',
    'Leesburg': 'United States',
    'Chantilly': 'United States',
    'Quantico': 'United States',
    'Fort Meade': 'United States',
    'Fort Rucker': 'United States',
    'Fort Wayne': 'United States',
    'Kings Bay Base': 'United States',
    'Minot Air Force Base': 'United States',
    'Huntsville': 'United States',
    'Pawtucket': 'United States',
    'Woonsocket': 'United States',
    'Cranston': 'United States',
    'Providence': 'United States',
    'Hartford': 'United States',
    'New Haven': 'United States',
    'Bridgeport': 'United States',
    'Stamford': 'United States',
    'Norwalk': 'United States',
    'Danbury': 'United States',
    'Dover': 'United States',
    'Wilmington': 'United States',
    'Newark': 'United States',
    'Milford': 'United States',
    'Bethlehem': 'United States',
    'Allentown': 'United States',
    'Reading': 'United States',
    'Erie': 'United States',
    'Scranton': 'United States',
    'Boise': 'United States',
    'Idaho Falls': 'United States',
    'Pocatello': 'United States',
    'Pocola': 'United States',
    'Stillwater': 'United States',
    'Norman': 'United States',
    'Broken Arrow': 'United States',
    'Edmond': 'United States',
    'Lawton': 'United States',
    'Missouri City': 'United States',
    'Sugar Land': 'United States',
    'The Woodlands': 'United States',
    'Pasadena': 'United States',
    'Pearland': 'United States',
    'Katy': 'United States',
    'League City': 'United States',
    'Baytown': 'United States',
    'Beaumont': 'United States',
    'Midland': 'United States',
    'Odessa': 'United States',
    'Lubbock': 'United States',
    'Amarillo': 'United States',
    'Abilene': 'United States',
    'Waco': 'United States',
    'Tyler': 'United States',
    'Texarkana': 'United States',
    'Robstown': 'United States',
    'Harlingen': 'United States',
    'McAllen': 'United States',
    'Laredo': 'United States',
    'El Paso': 'United States',
    'San Angelo': 'United States',
    'Rock Island': 'United States',
    'Moline': 'United States',
    'Quad Cities': 'United States',
    'Peoria': 'United States',
    'Springfield': 'United States',
    'Decatur': 'United States',
    'Bloomington': 'United States',
    'Normal': 'United States',
    'Carbondale': 'United States',
    'Joliet': 'United States',
    'Rockford': 'United States',
    'Elgin': 'United States',
    'Waukegan': 'United States',
    'Evanston': 'United States',
    'Schererville': 'United States',
    'Gary': 'United States',
    'Hammond': 'United States',
    'South Bend': 'United States',
    'Fort Wayne': 'United States',
    'Evansville': 'United States',
    'Terre Haute': 'United States',
    'Muncie': 'United States',
    'Anderson': 'United States',
    'Kokomo': 'United States',
    'Lafayette': 'United States',
    'Fishers': 'United States',
    'Carmel': 'United States',
    'Westfield': 'United States',
    'Noblesville': 'United States',
    'Greenwood': 'United States',
    'Johnson Creek': 'United States',
    'Reynoldsburg': 'United States',
    'Gahanna': 'United States',
    'Westerville': 'United States',
    'Dublin': 'United States',
    'New Albany': 'United States',
    'Grove City': 'United States',
    'Hilliard': 'United States',
    'Worthington': 'United States',
    'Upper Arlington': 'United States',
    'Bexley': 'United States',
    'Grandview Heights': 'United States',
    'Whitehall': 'United States',
    'Reynoldsburg': 'United States',
    'Groveport': 'United States',
    'Pickerington': 'United States',
    'Pataskala': 'United States',
    'Newark-on-Trent': 'United Kingdom',
    'Stratford': 'United Kingdom',
    'Warwick': 'United Kingdom',
    'Horsham': 'United Kingdom',
    'Farnborough': 'United Kingdom',
    'Knutsford': 'United Kingdom',
    'Macclesfield': 'United Kingdom',
    'Chesterfield': 'United Kingdom',
    'Bracknell': 'United Kingdom',
    'Coventry': 'United Kingdom',
    'Leicester': 'United Kingdom',
    'Nottingham': 'United Kingdom',
    'Derby': 'United Kingdom',
    'Sheffield': 'United Kingdom',
    'Leeds': 'United Kingdom',
    'Bradford': 'United Kingdom',
    'Wakefield': 'United Kingdom',
    'Huddersfield': 'United Kingdom',
    'Halifax': 'United Kingdom',
    'York': 'United Kingdom',
    'Hull': 'United Kingdom',
    'Newcastle': 'United Kingdom',
    'Newcastle upon Tyne': 'United Kingdom',
    'Sunderland': 'United Kingdom',
    'Middlesbrough': 'United Kingdom',
    'Middlesbrough': 'United Kingdom',
    'Durham': 'United Kingdom',
    'Gateshead': 'United Kingdom',
    'Dundee': 'United Kingdom',
    'Aberdeen': 'United Kingdom',
    'Inverness': 'United Kingdom',
    'Perth': 'United Kingdom',
    'Stirling': 'United Kingdom',
    'Cardiff': 'United Kingdom',
    'Swansea': 'United Kingdom',
    'Newport': 'United Kingdom',
    'Belfast': 'United Kingdom',
    'Londonderry': 'United Kingdom',
    'Derry': 'United Kingdom',
    'Royal Leamington Spa': 'United Kingdom',
    'Leamington Spa': 'United Kingdom',
    'Uxbridge': 'United Kingdom',
    'Berwick-upon-Tweed': 'United Kingdom',
    'Filey': 'United Kingdom',
    'Port Seton': 'United Kingdom',
    'Driffield': 'United Kingdom',
    'Bridlington': 'United Kingdom',
    'Ashby-de-la-Zouch': 'United Kingdom',
    'Burton upon Trent': 'United Kingdom',
    'Bath': 'United Kingdom',
    'Warrington': 'United Kingdom',
    'Shepton Mallet': 'United Kingdom',
    'Wilmslow': 'United Kingdom',
    'Southampton': 'United Kingdom',
    'Portsmouth': 'United Kingdom',
    'Basingstoke': 'United Kingdom',
    'Leatherhead': 'United Kingdom',
    'St Albans': 'United Kingdom',
    'Milton Keynes': 'United Kingdom',
    'Northampton': 'United Kingdom',
    'Peterborough': 'United Kingdom',
    'Ipswich': 'United Kingdom',
    'Norwich': 'United Kingdom',
    'Exeter': 'United Kingdom',
    'Plymouth': 'United Kingdom',
    'Truro': 'United Kingdom',
    'Dumfries': 'United Kingdom',
    'Cullompton': 'United Kingdom',
    'Chatham': 'United Kingdom',
    'Stafford': 'United Kingdom',
    'Lees': 'United Kingdom',
    'England': 'United Kingdom',
    'Scotland': 'United Kingdom',
    'Wales': 'United Kingdom',
    'Northern Ireland': 'United Kingdom',
    'UK': 'United Kingdom',
    'Britain': 'United Kingdom',
    'Great Britain': 'United Kingdom',
    'Time zones: NA, UK, EU': 'United Kingdom',
    # ── INDIA ──────────────────────────────────────────────
    'Bengaluru': 'India', 'Bangalore': 'India',
    'Mumbai': 'India', 'Pune': 'India',
    'Hyderabad': 'India', 'Chennai': 'India',
    'Kolkata': 'India', 'Delhi': 'India',
    'New Delhi': 'India', 'Noida': 'India',
    'Gurugram': 'India', 'Gurgaon': 'India',
    'Ahmedabad': 'India', 'Jaipur': 'India',
    'Surat': 'India', 'Lucknow': 'India',
    'Nagpur': 'India', 'Indore': 'India',
    'Bhopal': 'India', 'Visakhapatnam': 'India',
    'Navi Mumbai': 'India', 'Kochi': 'India',
    'Amritsar': 'India', 'Vadodara': 'India',
    'Agra': 'India', 'Thiruvananthapuram': 'India',
    'Faridabad': 'India', 'Lahore': 'India',
    'Kolhapur': 'India', 'Amravati': 'India',
    'Prayagraj': 'India', 'Warangal': 'India',
    'Malappuram': 'India', 'Panaji': 'India',
    'Singrauli': 'India', 'Bilaspur': 'India',
    'Jalgaon': 'India', 'Bhubaneswar': 'India',
    'Latambarcem': 'India',
    # ── CANADA ─────────────────────────────────────────────
    'Vancouver': 'Canada', 'Toronto': 'Canada',
    'Montreal': 'Canada', 'Calgary': 'Canada',
    'Ottawa': 'Canada', 'Edmonton': 'Canada',
    'Winnipeg': 'Canada', 'Quebec City': 'Canada',
    'Québec City': 'Canada', 'Hamilton': 'Canada',
    'Waterloo': 'Canada', 'Victoria': 'Canada',
    'Burnaby': 'Canada', 'Coquitlam': 'Canada',
    'Richmond Hill': 'Canada', 'Oakville': 'Canada',
    'Mississauga': 'Canada', 'Brampton': 'Canada',
    'Halifax': 'Canada', 'Saskatoon': 'Canada',
    'Regina': 'Canada', 'Kelowna': 'Canada',
    'New Westminster': 'Canada', 'Moncton': 'Canada',
    'Saguenay': 'Canada', 'Burlington': 'Canada',
    'Longueuil': 'Canada', 'Brossard': 'Canada',
    'Vancouver/Montreal': 'Canada',
    'Remote within BC': 'Canada',
    'USA/Canada preferred': 'Canada',
    # ── CHINA ──────────────────────────────────────────────
    'Shanghai': 'China', 'Beijing': 'China',
    'Shenzhen': 'China', 'Guangzhou': 'China',
    'Chengdu': 'China', 'Hangzhou': 'China',
    'Suzhou': 'China', 'Nanjing': 'China',
    'Wuhan': 'China', 'Tianjin': 'China',
    'Chongqing': 'China', 'Ningbo': 'China',
    'Shenyang': 'China', 'Foshan': 'China',
    'Hefei': 'China', 'Dongguan': 'China',
    'Dalian': 'China', 'Qingdao': 'China',
    'Zhengzhou': 'China', 'Xi\'An': 'China',
    'Changsha': 'China', 'Wuxi': 'China',
    'Shaoxing': 'China', 'Liaoyang': 'China',
    'Haixi Mongol and Tibetan Autonomous Prefecture': 'China',
    'Taipai': 'China',
    # ── GERMANY ────────────────────────────────────────────
    'Berlin': 'Germany', 'Munich': 'Germany',
    'Hamburg': 'Germany', 'Frankfurt': 'Germany',
    'Frankfurt am Main': 'Germany', 'Cologne': 'Germany',
    'Düsseldorf': 'Germany', 'Dusseldorf': 'Germany',
    'Stuttgart': 'Germany', 'Leipzig': 'Germany',
    'Dresden': 'Germany', 'Regensburg': 'Germany',
    'Hannover': 'Germany', 'Hanover': 'Germany',
    'Nuremberg': 'Germany', 'Bremen': 'Germany',
    'Bochum': 'Germany', 'Wolfsburg': 'Germany',
    'Warstein': 'Germany', 'Giebelstadt': 'Germany',
    'Karlsruhe': 'Germany', 'Mannheim': 'Germany',
    'Heidelberg': 'Germany', 'Freiburg': 'Germany',
    'Erlangen': 'Germany', 'Bayreuth': 'Germany',
    'Aachen': 'Germany', 'Wiesbaden': 'Germany',
    'Mainz': 'Germany', 'Kassel': 'Germany',
    'Braunschweig': 'Germany', 'Mönchengladbach': 'Germany',
    'Ettlingen': 'Germany', 'Heimsheim': 'Germany',
    'Bad Nauheim': 'Germany', 'Monschau': 'Germany',
    'Brunnthal': 'Germany', 'Pressig': 'Germany',
    'Eschborn': 'Germany', 'Würselen': 'Germany',
    'Papenburg': 'Germany', 'Warstein': 'Germany',
    'Gebze': 'Turkey',
    # ── POLAND ─────────────────────────────────────────────
    'Warsaw': 'Poland', 'Krakow': 'Poland',
    'Kraków': 'Poland', 'Wrocław': 'Poland',
    'Wroclaw': 'Poland', 'Gdańsk': 'Poland',
    'Gdansk': 'Poland', 'Poznan': 'Poland',
    'Lodz': 'Poland', 'Szczecin': 'Poland',
    'Bydgoszcz': 'Poland', 'Lublin': 'Poland',
    'Katowice': 'Poland', 'Białystok': 'Poland',
    'Zabierzów': 'Poland', 'Leonardów': 'Poland',
    'Cegléd': 'Hungary',
    # ── UKRAINE ────────────────────────────────────────────
    'Kyiv': 'Ukraine', 'Kiev': 'Ukraine',
    'Kharkiv': 'Ukraine', 'Odessa': 'Ukraine',
    'Dnipro': 'Ukraine', 'Lviv': 'Ukraine',
    'Zaporizhzhia': 'Ukraine', 'Vinnytsia': 'Ukraine',
    'Kherson': 'Ukraine', 'Mykolaiv': 'Ukraine',
    'Mariupol': 'Ukraine', 'Poltava': 'Ukraine',
    'Chernihiv': 'Ukraine', 'Sumy': 'Ukraine',
    'Zhytomyr': 'Ukraine', 'Rivne': 'Ukraine',
    'Ivano-Frankivsk': 'Ukraine', 'Ternopil': 'Ukraine',
    'Lutsk': 'Ukraine', 'Uzhhorod': 'Ukraine',
    'Ukrainka': 'Ukraine', 'Kyivets\'': 'Ukraine',
    # ── AUSTRALIA ──────────────────────────────────────────
    'Sydney': 'Australia', 'Melbourne': 'Australia',
    'Brisbane': 'Australia', 'Perth': 'Australia',
    'Adelaide': 'Australia', 'Canberra': 'Australia',
    'Gold Coast': 'Australia', 'Newcastle': 'Australia',
    'Sunshine Coast': 'Australia', 'Wollongong': 'Australia',
    'Hobart': 'Australia', 'Darwin': 'Australia',
    'Geelong': 'Australia', 'Townsville': 'Australia',
    'Cairns': 'Australia', 'Toowoomba': 'Australia',
    'North Ryde': 'Australia', 'Fortitude Valley': 'Australia',
    'Parramatta': 'Australia', 'Macquarie Park': 'Australia',
    'North Sydney': 'Australia', 'Batemans Bay': 'Australia',
    'Pakenham': 'Australia', 'Burleigh Heads': 'Australia',
    'Moranbah': 'Australia', 'South Hedland': 'Australia',
    'Rockhampton': 'Australia', 'Baldivis': 'Australia',
    'Kingaroy': 'Australia', 'Booragoon': 'Australia',
    'Carindale': 'Australia', 'Myaree': 'Australia',
    'Essendon North': 'Australia', 'Carnegie': 'Australia',
    'Cannington': 'Australia', 'Brunswick': 'Australia',
    'Mildura': 'Australia', 'Albury': 'Australia',
    'Mount Gambier': 'Australia', 'Nambour': 'Australia',
    'Tweed Heads': 'Australia', 'Hervey Bay': 'Australia',
    'Dubbo': 'Australia', 'Kalgoorlie - Boulder': 'Australia',
    'Dalby': 'Australia', 'Morley': 'Australia',
    'Bairnsdale': 'Australia', 'Rural City of Wangaratta': 'Australia',
    'Bennetts Green': 'Australia', 'Seven Hills': 'Australia',
    'Phillip': 'Australia', 'Greystanes': 'Australia',
    'Burleigh Heads': 'Australia',
    # ── FRANCE ─────────────────────────────────────────────
    'Paris': 'France', 'Lyon': 'France',
    'Marseille': 'France', 'Toulouse': 'France',
    'Nice': 'France', 'Nantes': 'France',
    'Strasbourg': 'France', 'Montpellier': 'France',
    'Bordeaux': 'France', 'Lille': 'France',
    'Rennes': 'France', 'Grenoble': 'France',
    'Annecy': 'France', 'Saint-Mandé': 'France',
    'Issy-les-Moulineaux': 'France',
    'Boulogne-Billancourt': 'France',
    'Courbevoie': 'France', 'Montreuil': 'France',
    'Levallois-Perret': 'France', 'Villeurbanne': 'France',
    'Aix-en-Provence': 'France', 'Montpelier': 'France',
    'Gémenos': 'France', 'Angoulême': 'France',
    'Le Bourget-du-Lac': 'France', 'La Vallée': 'France',
    'Bourogne': 'France', 'Carentoir': 'France',
    'Los Cristianos': 'Spain',
    # ── SPAIN ──────────────────────────────────────────────
    'Madrid': 'Spain', 'Barcelona': 'Spain',
    'Valencia': 'Spain', 'Seville': 'Spain',
    'Bilbao': 'Spain', 'Málaga': 'Spain',
    'Zaragoza': 'Spain', 'Palma': 'Spain',
    'Las Palmas': 'Spain', 'Murcia': 'Spain',
    'Alicante': 'Spain', 'Córdoba': 'Spain',
    'Valladolid': 'Spain', 'Vigo': 'Spain',
    'Girona': 'Spain', 'Tres Cantos': 'Spain',
    # ── SWEDEN ─────────────────────────────────────────────
    'Stockholm': 'Sweden', 'Gothenburg': 'Sweden',
    'Malmö': 'Sweden', 'Malmo': 'Sweden',
    'Uppsala': 'Sweden', 'Linköping': 'Sweden',
    'Örebro': 'Sweden', 'Västerås': 'Sweden',
    'Helsingborg': 'Sweden', 'Jönköping': 'Sweden',
    'Norrköping': 'Sweden', 'Lund': 'Sweden',
    'Boden': 'Sweden', 'Skövde': 'Sweden',
    'Aarhus': 'Denmark', 'Aalborg': 'Denmark',
    'Hørsholm': 'Denmark',
    # ── NETHERLANDS ────────────────────────────────────────
    'Amsterdam': 'Netherlands', 'Rotterdam': 'Netherlands',
    'The Hague': 'Netherlands', 'Utrecht': 'Netherlands',
    'Eindhoven': 'Netherlands', 'Groningen': 'Netherlands',
    'Alkmaar': 'Netherlands', 'Delft': 'Netherlands',
    'Zoetermeer': 'Netherlands', 'Wijchen': 'Netherlands',
    'Hilversum': 'Netherlands', 'Schiphol-Rijk': 'Netherlands',
    # ── ISRAEL ─────────────────────────────────────────────
    'Tel Aviv': 'Israel', 'Tel Aviv-Yafo': 'Israel',
    'Yokne\'am Illit': 'Israel', 'Herzliya': 'Israel',
    'Ra\'anana': 'Israel', 'Haifa': 'Israel',
    'Jerusalem': 'Israel', 'Beer Sheva': 'Israel',
    'Petah Tikva': 'Israel', 'Petah Tikva': 'Israel',
    'Rosh Haayin': 'Israel', 'Ramat Gan': 'Israel',
    'Rishon LeZion': 'Israel', 'Holon': 'Israel',
    'Bnei Brak': 'Israel', 'Netanya': 'Israel',
    'Ashdod': 'Israel', 'Be\'er Sheva': 'Israel',
    'Caesarea': 'Israel', 'Hsinchu': 'Taiwan',
    'Kaohsiung': 'Taiwan', 'Taipei': 'Taiwan',
    # ── JAPAN ──────────────────────────────────────────────
    'Tokyo': 'Japan', 'Osaka': 'Japan',
    'Kyoto': 'Japan', 'Yokohama': 'Japan',
    'Nagoya': 'Japan', 'Sapporo': 'Japan',
    'Fukuoka': 'Japan', 'Kobe': 'Japan',
    'Sendai': 'Japan', 'Hiroshima': 'Japan',
    'Kamakura': 'Japan', 'Amagasaki': 'Japan',
    'Akita': 'Japan', 'Shinjuku City': 'Japan',
    'Minato City': 'Japan', 'Shibuya': 'Japan',
    'Kodaira': 'Japan', 'Nagoya': 'Japan',
    'Hitachinaka': 'Japan', 'Yokohama': 'Japan',
    # ── SOUTH KOREA ────────────────────────────────────────
    'Seoul': 'South Korea', 'Busan': 'South Korea',
    'Incheon': 'South Korea', 'Daegu': 'South Korea',
    'Daejeon': 'South Korea', 'Gwangju': 'South Korea',
    'Suwon': 'South Korea', 'Ulsan': 'South Korea',
    'Seongnam-si': 'South Korea', 'Yongin-si': 'South Korea',
    # ── BRAZIL ─────────────────────────────────────────────
    'São Paulo': 'Brazil', 'Sao Paulo': 'Brazil',
    'Rio de Janeiro': 'Brazil', 'Belo Horizonte': 'Brazil',
    'Brasília': 'Brazil', 'Porto Alegre': 'Brazil',
    'Curitiba': 'Brazil', 'Manaus': 'Brazil',
    'Fortaleza': 'Brazil', 'Salvador': 'Brazil',
    'Brumadinho': 'Brazil', 'Santa Catarina': 'Brazil',
    # ── MEXICO ─────────────────────────────────────────────
    'Mexico City': 'Mexico', 'Ciudad de México': 'Mexico',
    'Guadalajara': 'Mexico', 'Monterrey': 'Mexico',
    'Puebla': 'Mexico', 'Tijuana': 'Mexico',
    'Juárez': 'Mexico', 'León': 'Mexico',
    'Zapopan': 'Mexico', 'Mérida': 'Mexico',
    'Merida': 'Mexico', 'San Andrés Cholula': 'Mexico',
    'Ciudad López Mateos': 'Mexico', 'Mexicali': 'Mexico',
    # ── OTHER COUNTRIES ────────────────────────────────────
    'Buenos Aires': 'Argentina', 'Mendoza': 'Argentina',
    'Córdoba': 'Argentina', 'Rosario': 'Argentina',
    'Junín': 'Argentina', 'Maldonado': 'Uruguay',
    'Montevideo': 'Uruguay', 'Asunción': 'Paraguay',
    'Santiago': 'Chile', 'Valparaíso': 'Chile',
    'Medellín': 'Colombia', 'Bogotá': 'Colombia',
    'Bogota': 'Colombia', 'Cali': 'Colombia',
    'Cúcuta': 'Colombia', 'Cartagena': 'Colombia',
    'Lima': 'Peru', 'Arequipa': 'Peru',
    'Quito': 'Ecuador', 'Guayaquil': 'Ecuador',
    'Cuenca': 'Ecuador', 'La Paz': 'Bolivia',
    'Asuncion': 'Paraguay',
    'Istanbul': 'Turkey', 'Ankara': 'Turkey',
    'İzmir': 'Turkey', 'Izmir': 'Turkey',
    'Antalya': 'Turkey', 'Bursa': 'Turkey',
    'Gaziantep': 'Turkey', 'Konya': 'Turkey',
    'Kayseri': 'Turkey',
    'Prague': 'Czech Republic', 'Brno': 'Czech Republic',
    'Cechia': 'Czech Republic', 'Czechia': 'Czech Republic',
    'Budapest': 'Hungary', 'Debrecen': 'Hungary',
    'Miskolc': 'Hungary', 'Pécs': 'Hungary',
    'Győr': 'Hungary',
    'Bucharest': 'Romania', 'Cluj': 'Romania',
    'Cluj-Napoca': 'Romania', 'Timișoara': 'Romania',
    'Iași': 'Romania', 'Brașov': 'Romania',
    'Constanța': 'Romania', 'Craiova': 'Romania',
    'Suceava': 'Romania', 'Varna': 'Bulgaria',
    'Plovdiv': 'Bulgaria', 'Sofia': 'Bulgaria',
    'Belgrade': 'Serbia', 'Novi Sad': 'Serbia',
    'Zagreb': 'Croatia', 'Split': 'Croatia',
    'Ljubljana': 'Slovenia', 'Maribor': 'Slovenia',
    'Skopje': 'North Macedonia',
    'Sarajevo': 'Bosnia and Herzegovina',
    'Tirana': 'Albania',
    'Vilnius': 'Lithuania', 'Kaunas': 'Lithuania',
    'Riga': 'Latvia', 'Tallinn': 'Estonia',
    'Tartu': 'Estonia',
    'Helsinki': 'Finland', 'Espoo': 'Finland',
    'Tampere': 'Finland', 'Turku': 'Finland',
    'Oulu': 'Finland',
    'Oslo': 'Norway', 'Bergen': 'Norway',
    'Trondheim': 'Norway',
    'Copenhagen': 'Denmark',
    'Zurich': 'Switzerland', 'Geneva': 'Switzerland',
    'Basel': 'Switzerland', 'Bern': 'Switzerland',
    'Schlieren': 'Switzerland', 'Oberentfelden': 'Switzerland',
    'Vienna': 'Austria', 'Graz': 'Austria',
    'Linz': 'Austria', 'Salzburg': 'Austria',
    'Villach': 'Austria', 'Spittal an der Drau': 'Austria',
    'Lisbon': 'Portugal', 'Porto': 'Portugal',
    'Braga': 'Portugal', 'Maia': 'Portugal',
    'Oeiras': 'Portugal', 'Minde': 'Portugal',
    'Athens': 'Greece', 'Thessaloniki': 'Greece',
    'Pylaia': 'Greece',
    'Nicosia': 'Cyprus', 'Limassol': 'Cyprus',
    'Paphos': 'Cyprus', 'Larnaca': 'Cyprus',
    'Dublin': 'Ireland', 'Cork': 'Ireland',
    'Galway': 'Ireland', 'Limerick': 'Ireland',
    'Kilkenny': 'Ireland', 'Waterford': 'Ireland',
    'Brussels': 'Belgium', 'Antwerp': 'Belgium',
    'Ghent': 'Belgium', 'Bruges': 'Belgium',
    'Liège': 'Belgium', 'Leuven': 'Belgium',
    'Mons': 'Belgium', 'Mol': 'Belgium',
    'Zaventem': 'Belgium',
    'Luxembourg': 'Luxembourg', 'Mondercange': 'Luxembourg',
    'Dubai': 'United Arab Emirates',
    'Abu Dhabi': 'United Arab Emirates',
    'Riyadh': 'Saudi Arabia', 'Jeddah': 'Saudi Arabia',
    'Dammam': 'Saudi Arabia',
    'King Abdullah Economic City': 'Saudi Arabia',
    'Rawabi': 'Palestine',
    'Cairo': 'Egypt', 'Alexandria': 'Egypt',
    'Lagos': 'Nigeria', 'Abuja': 'Nigeria',
    'Katsina': 'Nigeria',
    'Nairobi': 'Kenya', 'Kigali': 'Rwanda',
    'Johannesburg': 'South Africa',
    'Cape Town': 'South Africa',
    'Yerevan': 'Armenia',
    'Baku': 'Azerbaijan',
    'Almaty': 'Kazakhstan',
    'Minsk': 'Belarus',
    'Kuala Lumpur': 'Malaysia', 'Shah Alam': 'Malaysia',
    'Malacca': 'Malaysia', 'Kulim': 'Malaysia',
    'Ipoh': 'Malaysia', 'George Town': 'Malaysia',
    'Johor Bahru': 'Malaysia', 'Simpang Ampat': 'Malaysia',
    'Bangkok': 'Thailand', 'Pattaya City': 'Thailand',
    'Chiang Mai': 'Thailand',
    'Jakarta': 'Indonesia', 'Bandung': 'Indonesia',
    'Surabaya': 'Indonesia', 'Yogyakarta': 'Indonesia',
    'Ho Chi Minh City': 'Vietnam', 'Hanoi': 'Vietnam',
    'Da Nang': 'Vietnam', 'Quảng Ngãi': 'Vietnam',
    'Hạ Long': 'Vietnam',
    'Manila': 'Philippines', 'Taguig': 'Philippines',
    'Quezon City': 'Philippines',
    'Auckland': 'New Zealand', 'Wellington': 'New Zealand',
    'Christchurch': 'New Zealand', 'Hamilton': 'New Zealand',
    'Tauranga': 'New Zealand', 'Lower Hutt': 'New Zealand',
    'Singapore': 'Singapore',
    'Hong Kong': 'Hong Kong',
    'Taipei': 'Taiwan', 'Hsinchu': 'Taiwan',
    'Kaohsiung': 'Taiwan', 'Tainan': 'Taiwan',
    'Taichung': 'Taiwan', 'Taiwa': 'Taiwan',
    'Islamabad': 'Pakistan', 'Lahore': 'Pakistan',
    'Karachi': 'Pakistan',
    'Heredia': 'Costa Rica', 'Cartago': 'Costa Rica',
    'Panama City': 'Panama',
    'Lima': 'Peru', 'Miraflores': 'Peru',
    'Kingston': 'Jamaica',
    'Tegucigalpa': 'Honduras',
    'Colombo': 'Sri Lanka',
    'Dhaka': 'Bangladesh',
    'Accra': 'Ghana',
    'Tunis': 'Tunisia',
    'Casablanca': 'Morocco',
    'Gibraltar': 'Gibraltar',
    'Valletta': 'Malta', 'Sliema': 'Malta',
    'Ta\' Xbiex': 'Malta', 'Floriana': 'Malta',
    'Msida': 'Malta',
    'Saint-Mandé': 'France',
    'Issy-les-Moulineaux': 'France',
    'Remote - worldwide': 'Remote',
    'Remote': 'Remote',
}

CITY_TO_COUNTRY_SUPPLEMENT = {
    'Bratislava': 'Slovakia',
    'Brighton': 'United Kingdom',
    'Bristol': 'United Kingdom',
    'Cambridge': 'United Kingdom',
    'Edinburgh': 'United Kingdom',
    'Glasgow': 'United Kingdom',
    'Guildford': 'United Kingdom',
    'Köln': 'Germany',
    'Liverpool': 'United Kingdom',
    'London': 'United Kingdom',
    'Manchester': 'United Kingdom',
    'Medellin': 'Colombia',
    'Moscow': 'Russia',
    'Novosibirsk': 'Russia',
    'Oxford': 'United Kingdom',
    'Saint Petersburg': 'Russia',
    'Singapore City': 'Singapore',
    'St. Petersburg': 'Russia',
}
